import requests
import json
import time
import re
import os
from bs4 import BeautifulSoup

class AIMemory:
    def __init__(self):
        self.memory_file = os.path.join("config", "ai_memory.json")
        self.memory = self._load_memory()

    def _load_memory(self):
        """Loads historical AI failures and user rules from disk."""
        if os.path.exists(self.memory_file):
            try:
                with open(self.memory_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    
                    if "problem_urls" in data and "rules" not in data:
                        return {"failures": data["problem_urls"], "rules": {}}
                    return data
            except Exception:
                pass
                
        return {"failures": {}, "rules": {}}

    def _save_memory(self):
        """Saves the current memory state to disk."""
        os.makedirs(os.path.dirname(self.memory_file), exist_ok=True)
        try:
            with open(self.memory_file, 'w', encoding='utf-8') as f:
                json.dump(self.memory, f, indent=4)
        except Exception as e:
            print(f"Failed to save AIMemory: {e}")

    def remember_failure(self, url, reason):
        """Logs that the standard scraper fails on this URL."""
        if url not in self.memory["failures"]:
            self.memory["failures"][url] = {
                "failed_count": 1,
                "reason": reason,
                "action": "bypass_regex_use_ai_directly"
            }
        else:
            self.memory["failures"][url]["failed_count"] += 1
            
        self._save_memory()

    def add_user_rule(self, url, rule):
        """Saves a custom user directive for a specific URL."""
        self.memory["rules"][url] = rule
        
        if url in self.memory["failures"]:
            del self.memory["failures"][url]
            
        self._save_memory()

    def is_known_problem(self, url):
        """Checks if the scraper should avoid standard methods for this URL."""
        return url in self.memory["rules"] or url in self.memory["failures"]
        
    def get_rule_for_url(self, url):
        """Retrieves the custom rule to inject into the Ollama AI prompt."""
        return self.memory["rules"].get(url, None)


class OllamaAI:
    def __init__(self, model_string="qwen2.5:14b", host="http://localhost:11434"):
        selected = str(model_string or "").strip()
        if selected.lower() in {
            "",
            "off",
            "regular",
            "regular (regex)",
            "regex",
        }:
            self.model = None
        else:
            self.model = selected.split()[0]
        self.host = host
        self.supplier_rules = self._load_ai_prompts()
        self.memory = AIMemory()

    def _load_ai_prompts(self) -> dict:
        """Loads the dynamic supplier rules from the config JSON file."""
        possible_paths = [
            "config/ai_prompts.json",
            os.path.join("..", "config", "ai_prompts.json"),
            os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "config", "ai_prompts.json")
        ]
        
        for path in possible_paths:
            if os.path.exists(path):
                try:
                    with open(path, 'r', encoding='utf-8') as f:
                        return json.load(f)
                except Exception as e:
                    print(f"Error loading ai_prompts.json: {e}")
        return {}

    def _clean_response(self, text: str) -> str:
        """Removes <think>...</think> tags generated by DeepSeek-R1."""
        cleaned = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL)
        return cleaned.strip()

    def manual_ai_extraction(
        self,
        url: str,
    ) -> tuple:
        if not self.model:
            return "", "UNKNOWN"

        try:
            import cloudscraper

            response = (
                cloudscraper
                .create_scraper()
                .get(
                    url,
                    timeout=20,
                )
            )

            if response.status_code != 200:
                return "", "UNKNOWN"

            visible_text = BeautifulSoup(
                response.text,
                "html.parser",
            ).get_text(
                " ",
                strip=True,
            )

            lower_text = visible_text.lower()

            blocked_phrases = (
                "access denied",
                "pardon our interruption",
                "additional security check",
                "are you a human",
                "verify you are human",
                "cloudflare",
                "enable javascript",
                "captcha",
            )

            if (
                any(
                    phrase in lower_text
                    for phrase in blocked_phrases
                )
                or len(visible_text) < 300
            ):
                return "", "UNKNOWN"

            explicit_oos_phrases = (
                "this product is no longer available",
                "product you are looking for "
                "is no longer available",
                "item is no longer available",
            )

            if any(
                phrase in lower_text
                for phrase in explicit_oos_phrases
            ):
                return "", "OOS"

            custom_rule = (
                self.memory.get_rule_for_url(url)
            )

            directive = ""

            if custom_rule:
                directive = (
                    "\nUSER DIRECTIVE: "
                    f"{custom_rule!r}. "
                    "Follow it only when the page "
                    "evidence supports it.\n"
                )

            prompt = (
                "Use only the supplied page text. "
                "Never guess.\n"
                f"{directive}"
                "Return exactly: PRICE | STOCK\n"
                "STOCK must be IN STOCK, "
                "OOS, or UNKNOWN.\n"
                f"PAGE TEXT:\n"
                f"{visible_text[:10000]}"
            )

            ai_response = requests.post(
                f"{self.host}/api/generate",
                json={
                    "model": self.model,
                    "prompt": prompt,
                    "stream": False,
                },
                timeout=45,
            )

            if ai_response.status_code != 200:
                return "", "UNKNOWN"

            raw_result = self._clean_response(
                ai_response.json().get(
                    "response",
                    "",
                )
            ).strip()

            parts = [
                part.strip()
                for part in raw_result.split(
                    "|",
                    1,
                )
            ]

            if len(parts) != 2:
                return "", "UNKNOWN"

            price_text, stock_text = parts
            stock_upper = stock_text.upper()

            if stock_upper not in {
                "IN STOCK",
                "OOS",
                "UNKNOWN",
            }:
                return "", "UNKNOWN"

            if price_text.upper() in {
                "",
                "N/A",
                "NA",
                "NONE",
                "NULL",
            }:
                price_text = ""

            if stock_upper == "UNKNOWN":
                price_text = ""

            return price_text, stock_upper

        except Exception as exc:
            print(
                "Manual AI extraction failed: "
                f"{type(exc).__name__}: {exc}"
            )
            return "", "UNKNOWN"

    def match_variation(self, target: str, available_options: list) -> str:
        """
        Bulletproof matching logic utilizing exact, token-subset, and semantic AI methods.
        """
        if not target or not available_options:
            return None
            
        target_clean = target.lower().strip()
        opts_clean = [opt.lower().strip() for opt in available_options]

        # 1. Exact Match Check
        if target_clean in opts_clean:
            return available_options[opts_clean.index(target_clean)]

        # 2. Token-Subset Heuristic Match (Prevents "Large" from matching "Extra Large")
        target_tokens = set(re.findall(r'[a-z0-9]+', target_clean))
        
        best_match = None
        best_diff = float('inf')

        if target_tokens:
            for i, opt in enumerate(opts_clean):
                opt_tokens = set(re.findall(r'[a-z0-9]+', opt))
                
                # If ALL words from the target exist inside this option
                if target_tokens.issubset(opt_tokens):
                    # Calculate how much "fluff" is left over. 
                    # If target is "Large", "Large" has 0 fluff. "Extra Large" has 1 fluff.
                    diff = len(opt_tokens) - len(target_tokens)
                    if diff < best_diff:
                        best_diff = diff
                        best_match = available_options[i]
            
            if best_match:
                return best_match

        # 3. AI Semantic Fallback (If text completely differs, e.g. "OD Green" vs "Olive Drab")
        prompt = (
            f"You are a strict data matcher. The user is looking for the product variation: '{target}'.\n"
            f"The available options on the website are: {json.dumps(available_options)}.\n"
            "Return ONLY the exact string from the available options array that logically means the exact same thing as the user's requested variation. "
            "If none of the options are a logical match, return exactly the word 'NONE'. "
            "Do not include quotes, explanations, or any other text in your response."
        )

        try:
            response = requests.post(f"{self.host}/api/generate", json={
                "model": self.model,
                "prompt": prompt,
                "stream": False
            }, timeout=15)
            
            if response.status_code == 200:
                raw_result = response.json().get("response", "")
                result = self._clean_response(raw_result).strip("\"'")
                
                if result == "NONE":
                    return None
                    
                # Ensure the AI didn't hallucinate a fake option
                for opt in available_options:
                    if result.lower().strip() == opt.lower().strip():
                        return opt
                        
                for opt in available_options:
                    if result.lower().strip() in opt.lower().strip():
                        return opt
                        
        except Exception as e:
            print(f"Ollama Variation Matching failed: {e}")
            
        return None

    def verify_scrape(
        self,
        url: str,
        price: str,
        stock: str,
        supplier: str = "",
    ):
        if not self.model:
            return None

        try:
            import cloudscraper

            response = (
                cloudscraper
                .create_scraper()
                .get(
                    url,
                    timeout=20,
                )
            )

            if response.status_code != 200:
                return None

            visible_text = BeautifulSoup(
                response.text,
                "html.parser",
            ).get_text(
                " ",
                strip=True,
            )

            lower_text = visible_text.lower()

            blocked_phrases = (
                "access denied",
                "pardon our interruption",
                "additional security check",
                "are you a human",
                "verify you are human",
                "cloudflare",
                "enable javascript",
                "captcha",
            )

            if (
                any(
                    phrase in lower_text
                    for phrase in blocked_phrases
                )
                or len(visible_text) < 300
            ):
                return None

            supplier_rule = (
                self.supplier_rules.get(
                    supplier,
                    "Evaluate normal "
                    "e-commerce evidence.",
                )
            )

            custom_rule = (
                self.memory.get_rule_for_url(url)
            )

            directive = ""

            if custom_rule:
                directive = (
                    "\nUSER DIRECTIVE: "
                    f"{custom_rule!r}. "
                    "Follow it only when "
                    "supported by evidence.\n"
                )

            prompt = (
                "Use only the supplied page text. "
                "Never guess.\n"
                f"Supplier rule: "
                f"{supplier_rule}\n"
                f"{directive}"
                f"Scraper price: {price}\n"
                f"Scraper stock: {stock}\n"
                "Reply with exactly "
                "YES, NO, or UNSURE.\n"
                f"PAGE TEXT:\n"
                f"{visible_text[:10000]}"
            )

            ai_response = requests.post(
                f"{self.host}/api/generate",
                json={
                    "model": self.model,
                    "prompt": prompt,
                    "stream": False,
                },
                timeout=45,
            )

            if ai_response.status_code != 200:
                return None

            answer = self._clean_response(
                ai_response.json().get(
                    "response",
                    "",
                )
            ).strip().upper()

            if answer:
                token = (
                    answer
                    .split(maxsplit=1)[0]
                    .strip(".,:;!?")
                )
            else:
                token = ""

            if token == "YES":
                return True

            if token == "NO":
                return False

            return None

        except Exception as exc:
            print(
                "Ollama verification failed: "
                f"{type(exc).__name__}: {exc}"
            )
            return None

class CaptchaSolver:
    def __init__(self, api_key=""):
        self.api_key = api_key
        
    def solve_perimeterx(self, page_url, site_key="PXu6b0qd2S"):
        if not self.api_key:
            return None
        try:
            submit_res = requests.post("http://2captcha.com/in.php", data={
                "key": self.api_key,
                "method": "perimeterx",
                "app_id": site_key,
                "pageurl": page_url,
                "json": 1
            }).json()
            
            if submit_res.get("status") != 1:
                return None
                
            request_id = submit_res.get("request")
            
            for _ in range(24):
                time.sleep(5)
                check_res = requests.get(f"http://2captcha.com/res.php?key={self.api_key}&action=get&id={request_id}&json=1").json()
                if check_res.get("status") == 1:
                    return check_res.get("request")
                    
        except Exception as e:
            print(f"2Captcha Solver failed: {e}")
            
        return None
