import requests
import json
import time
import re
import os
from bs4 import BeautifulSoup

class AIMemory:
    def __init__(self):
        self.memory_file = os.path.join("config", "ai_memory.json")
        self.memory = self._load_memory()

    def _load_memory(self):
        """Loads historical AI failures and user rules from disk."""
        if os.path.exists(self.memory_file):
            try:
                with open(self.memory_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    
                    if "problem_urls" in data and "rules" not in data:
                        return {"failures": data["problem_urls"], "rules": {}}
                    return data
            except Exception:
                pass
                
        return {"failures": {}, "rules": {}}

    def _save_memory(self):
        """Saves the current memory state to disk."""
        os.makedirs(os.path.dirname(self.memory_file), exist_ok=True)
        try:
            with open(self.memory_file, 'w', encoding='utf-8') as f:
                json.dump(self.memory, f, indent=4)
        except Exception as e:
            print(f"Failed to save AIMemory: {e}")

    def remember_failure(self, url, reason):
        """Logs that the standard scraper fails on this URL."""
        if url not in self.memory["failures"]:
            self.memory["failures"][url] = {
                "failed_count": 1,
                "reason": reason,
                "action": "bypass_regex_use_ai_directly"
            }
        else:
            self.memory["failures"][url]["failed_count"] += 1
            
        self._save_memory()

    def add_user_rule(self, url, rule):
        """Saves a custom user directive for a specific URL."""
        self.memory["rules"][url] = rule
        
        if url in self.memory["failures"]:
            del self.memory["failures"][url]
            
        self._save_memory()

    def is_known_problem(self, url):
        """Checks if the scraper should avoid standard methods for this URL."""
        return url in self.memory["rules"] or url in self.memory["failures"]
        
    def get_rule_for_url(self, url):
        """Retrieves the custom rule to inject into the Ollama AI prompt."""
        return self.memory["rules"].get(url, None)


class OllamaAI:
    def __init__(self, model_string="qwen2.5:14b", host="http://localhost:11434"):
        self.model = model_string.split(" ")[0].lower() if model_string else "qwen2.5:14b"
        self.host = host
        self.supplier_rules = self._load_ai_prompts()
        self.memory = AIMemory()

    def _load_ai_prompts(self) -> dict:
        """Loads the dynamic supplier rules from the config JSON file."""
        possible_paths = [
            "config/ai_prompts.json",
            os.path.join("..", "config", "ai_prompts.json"),
            os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "config", "ai_prompts.json")
        ]
        
        for path in possible_paths:
            if os.path.exists(path):
                try:
                    with open(path, 'r', encoding='utf-8') as f:
                        return json.load(f)
                except Exception as e:
                    print(f"Error loading ai_prompts.json: {e}")
        return {}

    def _clean_response(self, text: str) -> str:
        """Removes <think>...</think> tags generated by DeepSeek-R1."""
        cleaned = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL)
        return cleaned.strip()

    def manual_ai_extraction(self, url: str) -> tuple:
        """Used ONLY for URLs that the scraper knows it fails on (Self-Awareness)."""
        try:
            import cloudscraper
            scraper = cloudscraper.create_scraper()
            r = scraper.get(url, timeout=15)
            if r.status_code != 200:
                return "", "OOS"
                
            soup = BeautifulSoup(r.text, "html.parser")
            visible_text = soup.get_text(" ", strip=True)
            
            lower_text = visible_text.lower()
            if any(phrase in lower_text for phrase in [
                "access denied", "pardon our interruption", "additional security check",
                "it may have moved or no longer exists", "can not be found", "no longer available"
            ]):
                return "", "OOS"

            visible_text = visible_text[:10000]
            
            custom_user_rule = self.memory.get_rule_for_url(url)
            user_directive_string = ""
            if custom_user_rule:
                user_directive_string = f"\nCRITICAL USER DIRECTIVE FOR THIS URL: '{custom_user_rule}'. You MUST obey this directive above all standard extraction rules.\n"
            
            prompt = (
                "You are an expert e-commerce data extractor.\n"
                "Read the following webpage text and extract the current Price and Stock Status.\n"
                f"{user_directive_string}"
                "Reply strictly and ONLY in this exact format: $XX.XX | [In Stock / OOS]\n"
                "If the price is hidden or missing, return: N/A | [In Stock / OOS]\n"
                f"---START TEXT---\n{visible_text}\n---END TEXT---"
            )
            
            response = requests.post(f"{self.host}/api/generate", json={
                "model": self.model,
                "prompt": prompt,
                "stream": False
            }, timeout=45)

            if response.status_code == 200:
                raw_result = self._clean_response(response.json().get("response", ""))
                
                parts = raw_result.split("|")
                if len(parts) >= 2:
                    price = parts[0].strip()
                    if "N/A" in price or "null" in price.lower():
                        price = ""
                    
                    stock_str = parts[1].strip().lower()
                    stock = "In Stock" if "in stock" in stock_str else "OOS"
                    return price, stock
        except Exception as e:
            print(f"Manual AI Extraction failed: {e}")
            
        return "", "OOS"

    def match_variation(self, target: str, available_options: list) -> str:
        """
        Bulletproof matching logic utilizing exact, token-subset, and semantic AI methods.
        """
        if not target or not available_options:
            return None
            
        target_clean = target.lower().strip()
        opts_clean = [opt.lower().strip() for opt in available_options]

        # 1. Exact Match Check
        if target_clean in opts_clean:
            return available_options[opts_clean.index(target_clean)]

        # 2. Token-Subset Heuristic Match (Prevents "Large" from matching "Extra Large")
        target_tokens = set(re.findall(r'[a-z0-9]+', target_clean))
        
        best_match = None
        best_diff = float('inf')

        if target_tokens:
            for i, opt in enumerate(opts_clean):
                opt_tokens = set(re.findall(r'[a-z0-9]+', opt))
                
                # If ALL words from the target exist inside this option
                if target_tokens.issubset(opt_tokens):
                    # Calculate how much "fluff" is left over. 
                    # If target is "Large", "Large" has 0 fluff. "Extra Large" has 1 fluff.
                    diff = len(opt_tokens) - len(target_tokens)
                    if diff < best_diff:
                        best_diff = diff
                        best_match = available_options[i]
            
            if best_match:
                return best_match

        # 3. AI Semantic Fallback (If text completely differs, e.g. "OD Green" vs "Olive Drab")
        prompt = (
            f"You are a strict data matcher. The user is looking for the product variation: '{target}'.\n"
            f"The available options on the website are: {json.dumps(available_options)}.\n"
            "Return ONLY the exact string from the available options array that logically means the exact same thing as the user's requested variation. "
            "If none of the options are a logical match, return exactly the word 'NONE'. "
            "Do not include quotes, explanations, or any other text in your response."
        )

        try:
            response = requests.post(f"{self.host}/api/generate", json={
                "model": self.model,
                "prompt": prompt,
                "stream": False
            }, timeout=15)
            
            if response.status_code == 200:
                raw_result = response.json().get("response", "")
                result = self._clean_response(raw_result).strip("\"'")
                
                if result == "NONE":
                    return None
                    
                # Ensure the AI didn't hallucinate a fake option
                for opt in available_options:
                    if result.lower().strip() == opt.lower().strip():
                        return opt
                        
                for opt in available_options:
                    if result.lower().strip() in opt.lower().strip():
                        return opt
                        
        except Exception as e:
            print(f"Ollama Variation Matching failed: {e}")
            
        return None

    def verify_scrape(self, url: str, price: str, stock: str, supplier: str = "") -> bool:
        """Acts as the 'AI Eyes' during the Suspicion Loop."""
        try:
            import cloudscraper
            scraper = cloudscraper.create_scraper()
            r = scraper.get(url, timeout=15)
            
            if r.status_code != 200:
                return True 
                
            soup = BeautifulSoup(r.text, "html.parser")
            visible_text = soup.get_text(" ", strip=True)
            
            lower_text = visible_text.lower()
            auto_approve_phrases = [
                "pardon our interruption", 
                "access denied", 
                "additional security check", 
                "are you a human", 
                "cloudflare",
                "enable javascript",
                "it may have moved or no longer exists",
                "the page you are looking for can not be found",
                "product you are looking for is no longer available"
            ]
            
            if any(phrase in lower_text for phrase in auto_approve_phrases) or len(visible_text) < 300:
                return True 

            visible_text = visible_text[:10000] 

            dynamic_rule = self.supplier_rules.get(supplier, "Evaluate standard e-commerce logic.")
            
            custom_user_rule = self.memory.get_rule_for_url(url)
            user_directive_string = ""
            if custom_user_rule:
                user_directive_string = f"\nCRITICAL USER DIRECTIVE FOR THIS URL: '{custom_user_rule}'. You MUST obey this directive above all standard rules.\n"

            prompt = (
                f"You are an expert e-commerce data validator.\n"
                f"Supplier-Specific Instructions: {dynamic_rule}\n"
                f"{user_directive_string}\n"
                f"A Regex scraper evaluated this webpage and concluded:\n"
                f"Price: {price}\n"
                f"Stock Status: {stock}\n\n"
                f"Here is the raw text scraped from the webpage:\n"
                f"---START TEXT---\n{visible_text}\n---END TEXT---\n\n"
                f"Based purely on the text provided, is the scraper's conclusion likely correct? "
                f"Reply with exactly 'YES' if it is correct, or 'NO' if it is obviously wrong. "
                f"If you are unsure or the text is too messy to tell, reply 'YES'."
            )
            
            response = requests.post(f"{self.host}/api/generate", json={
                "model": self.model,
                "prompt": prompt,
                "stream": False
            }, timeout=45)

            if response.status_code == 200:
                raw_result = response.json().get("response", "")
                result = self._clean_response(raw_result).upper()
                
                if "NO" in result and "YES" not in result:
                    return False
                    
        except Exception as e:
            print(f"Ollama Verification failed: {e}")
        
        return True


class CaptchaSolver:
    def __init__(self, api_key=""):
        self.api_key = api_key
        
    def solve_perimeterx(self, page_url, site_key="PXu6b0qd2S"):
        if not self.api_key:
            return None
        try:
            submit_res = requests.post("http://2captcha.com/in.php", data={
                "key": self.api_key,
                "method": "perimeterx",
                "app_id": site_key,
                "pageurl": page_url,
                "json": 1
            }).json()
            
            if submit_res.get("status") != 1:
                return None
                
            request_id = submit_res.get("request")
            
            for _ in range(24):
                time.sleep(5)
                check_res = requests.get(f"http://2captcha.com/res.php?key={self.api_key}&action=get&id={request_id}&json=1").json()
                if check_res.get("status") == 1:
                    return check_res.get("request")
                    
        except Exception as e:
            print(f"2Captcha Solver failed: {e}")
            
        return None